name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t vklekler/docker-react -f Dockerfile.dev .
           docker run -e CI=TRUE vklekler/docker-react npm run test -- --coverage
